### PR TITLE
Add recursive directory searching

### LINKED ISSUE #14: Recursive directory search
Right now the app loads the files from a single directory ignoring any sub-directory. Change the search to be recursive taking performance into account.

### PR DESCRIPTION
**Pull request by cnorick**
Fixes #14.

### CODE REVIEW

**Comment by fdiogo** [comment]
Does it need to synchronous? You can easily make it async :)

**Comment by cnorick** [comment]
You're right, @fdiogo. I completely looked over that. Changing it now. :)

**Comment by cnorick** [comment]
The stat call is now async.

**Comment by fdiogo** [comment]
Thanks for contribution @cnorick!

**Pull request merged**
